### ISSUE TITLE
显示/隐藏工具栏的快捷键 f 会和 vimium 的 f 键功能冲突

### ISSUE THREAD

**Issue by tjx666** [gp5251/better_ruler#1]
考虑使用别的快捷键为显示/隐藏工具栏的默认快捷键，或者允许用户自定义快捷键？

**Comment by tjx666** [comment]
希望可以支持 ESC 键退出扩展

**Comment by gp5251** [comment]
可以手动指定快捷键启动和退出插件。 chrome://extensions/shortcuts
